### ISSUE TITLE
Build Environment ?

### ISSUE THREAD

**Issue by kub3let** [GZR-Kernels/Optimus_Drunk_Surya#6]
Google has blacklisted custom kernel names, which includes `Optimus` to pass SafetyNet/Google Play Integrity. https://xdaforums.com/t/module-play-integrity-fix-safetynet-fix.4607985/post-89308909

I'm trying to build the [v11.24](https://github.com/GZR-Kernels/Optimus_Drunk_Surya/releases/tag/v11.24) myself without the kernel name to bypass the blacklist, but I only get from one error to the next.

What is required to build these Kernels ? e.g. clang version, etc. ?

**Comment by GtrCraft** [comment]
This kernel is EOL, I doubt you can even build it still.
